### ISSUE TITLE
Inferred type is String? but Any was expected.

### ISSUE THREAD

**Issue by gsbruno** [InvisibleWrench/FlutterMidiCommand#31] opened 2021-04-26 18:22 UTC
Hello, first thanks for the package, very useful.

I found a problem in the following code snippet(File: FlutterMidiCommandPlugin.kt, Line: 389, Column: 34). 

Error: Inferred type is String? but Any was expected.
```kotlin
fun listOfDevices() : List<Map<String, Any>> {
    var list = mutableListOf<Map<String, Any>>()

    val devs:Array<MidiDeviceInfo> = midiManager.devices
    Log.d("FlutterMIDICommand", "devices $devs")
    devs.forEach { d -> list.add(mapOf(
            "name" to d.properties.getString(MidiDeviceInfo.PROPERTY_NAME),
            "id" to d.id.toString(),
            "type" to "native",
            "connected" to if (connectedDevices.contains(d.id.toString())) "true" else "false",
            "inputs" to listOfPorts(d.inputPortCount),
            "outputs" to listOfPorts(d.outputPortCount)
          )
    )}
```
It must be something related to a kotlin update where the type Any is not used for null, but Any? works.

Again, thanks for the package.

**Comment by mortenboye** [comment] 2021-04-26 18:47
It's unclear to me what the issue is. What kinds of errors are you seeing?

**Comment by gsbruno** [comment] 2021-04-26 19:02
Sorry about that, the error is in the title. Inferred type is String? but Any was expected.

**Comment by mortenboye** [comment] 2021-04-26 19:14
Ah yes. I found it, fixing now.

**Comment by mortenboye** [comment] 2021-04-26 19:19
@gsbruno fixed in https://github.com/InvisibleWrench/FlutterMidiCommand/commit/8e2f8bcb20367fe6425171e3d454c7ef4ba39672

**Closed by mortenboye** 2021-04-26 19:19 UTC

**Comment by gsbruno** [comment] 2021-04-26 19:24
Thanks for the quick feedback.
